name: Checkstyle Verification

on:
  push:
    branches:
      - main
      - master
      - 'your-branch-name'  # Add other branches if needed
  pull_request:
    branches:
      - main
      - master
      - 'your-branch-name'

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Checkstyle check
        run: ./gradlew checkstyleMain checkstyleTest --continue
