name: Checkstyle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3

      - name: Настройка JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Проверка зависимостей Gradle
        run: ./gradlew dependencies

      - name: Запуск Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest
